ExpTechTW/DPIP

- lib/view/earthquake.dart
> Fix: eew screen display

- ios/Runner/AppDelegate.swift
- ios/Runner/Info.plist
- lib/util/magnitude_color.dart
- lib/view/me.dart
- lib/view/report.dart
- lib/view/setting/location.dart
- lib/widget/report/image_field.dart
> fix: ios map basemap selection reset

- lib/view/report.dart
- lib/view/report_list.dart
- lib/widget/earthquake_report_list_tile.dart
> fix: ios depth

- .gitignore
- README.md
- lib/view/me.dart
- lib/view/notify.dart
> Revert "refactor: Audio UI"

- lib/view/earthquake.dart
- lib/view/report.dart
> feat: earthquake time

- lib/model/tsunami/tsunami.dart
- lib/model/tsunami/tsunami_actual.dart
- lib/model/tsunami/tsunami_earthquake.dart
- lib/model/tsunami/tsunami_estimate.dart
- lib/model/tsunami/tsunami_info.dart
> 選擇所有符合的項目
新增海嘯 data model
- 無
- 無
> feat: tsunami data model

- lib/route/settings/content/location.dart
> 選擇所有符合的項目
新增 開關自動定位時回傳最後位置
- 無
- 無
> feat: auto-location-send

- lib/route/settings/content/location.dart
> 選擇所有符合的項目
修正 啟用自動定位 的開關 無法關閉的 BUG
- 無
- 無
> fix: auto-location-Turn-off-bug

- lib/route/settings/content/location.dart
- pubspec.yaml
> 選擇所有符合的項目
修正 啟用自動定位 的開關 無法關閉的 BUG
- 無
- 無
> Fix auto location turn off bug

- .github/workflows/github_actions.yml
- android/app/build.gradle
> 選擇所有符合的項目
- 相關問題 #
- closes #
> fix: github action

- ios/Podfile
- ios/Podfile.lock
- ios/Runner/AppDelegate.swift
> 選擇所有符合的項目
ios強制更新
- 相關問題 #
- closes #136 
> feat: IOS forced update

- lib/route/settings/content/root.dart
- pubspec.lock
- pubspec.yaml
> 選擇所有符合的項目
複製 FCM Token
- 無
- 無
> feat: copy-FCM-Token

- .github/workflows/github_actions.yml
- ios/Runner/AppDelegate.swift
- lib/core/location.dart
- lib/core/service.dart
- lib/main.dart
- lib/route/report/report.dart
- lib/route/settings/content/location.dart
- lib/route/settings/content/root.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> Refactor ios location

- pubspec.yaml
> 選擇所有符合的項目
- 相關問題 #
- closes #
> build: 2.0.25

- .gitignore
- ios/Runner.xcodeproj/project.pbxproj
- lib/widget/report/list_item.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> fix: iOS sound name

- lib/app/page/map/tsunami.dart
- lib/model/tsunami/tsunami.dart
> Fix tsunami UI

- lib/main.dart
> 選擇所有符合的項目
修復 Android 底下導覽列沒有依照主題有透明效果．
- 相關問題 #
- closes #
> fix-導覽列透明效果

- lib/route/settings/content/location.dart
- pubspec.lock
> 選擇所有符合的項目
- 相關問題 #
- closes #
> fix: android location button

- ios/Podfile.lock
- lib/route/report/report.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
> 選擇所有符合的項目
- 相關問題 #
- closes #
> fix: map draw

- lib/route/settings/content/location.dart
> 選擇所有符合的項目
打開自動定位清除所在地選單
- 相關問題 #
- closes #
> fix: location menu

- lib/api/exptech.dart
- lib/api/route.dart
- lib/app/page/report_list/report_list.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> feat: infinity scrolling

- lib/route/settings/content/location.dart
- lib/route/settings/content/root.dart
- lib/route/settings/content/sound.dart
- lib/route/settings/content/theme.dart
- lib/util/extension/build_context.dart
> 選擇所有符合的項目
修正導航列和程式內容重疊的問題
- 相關問題 #
- closes #
| 修正前 | 修正後 |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/93490253-3f8c-409b-b451-5e7f5a3aec8a) | ![image](https://github.com/user-attachments/assets/04b04b4e-1175-4885-bc4c-907340894fa7) |
> fix: restore listview bottom padding

- lib/app/page/me/me.dart
- lib/l10n/app_zh_TW.arb
- pubspec.lock
> 選擇所有符合的項目
- 相關問題 #
- closes #
> chore: change instagram to threads

- lib/l10n/app_zh_TW.arb
- lib/route/report/report_sheet_content.dart
- lib/widget/report/list_item.dart
> 選擇所有符合的項目
報告頁面翻譯 token
- 相關問題 #
- closes #
> i18n(ReportRoute): tokenize texts

- lib/core/service.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> fix: notify body

- lib/route/report/report.dart
- lib/route/report/report_sheet_content.dart
- lib/util/extension/color_scheme.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> feat: report page tsunami

- lib/app/page/monitor/monitor.dart
- pubspec.yaml
> 選擇所有符合的項目
- 相關問題 #
- closes #
> fix: time ui color

- pubspec.lock
- pubspec.yaml
> 選擇所有符合的項目
- 相關問題 #
- closes #
> chore: Current dependent library version

- lib/route/report/report.dart
- lib/widget/map/map.dart
> 選擇所有符合的項目
地震報告 Ｓ 波抵達同心環
- 相關問題 #
- closes #
> feat: report wave

- lib/widget/map/map.dart
- pubspec.yaml
> 選擇所有符合的項目
調整手機裝置螢幕大小
- 相關問題 #
- closes #
> Fix: map zoom

- lib/app/page/monitor/monitor.dart
> 選擇所有符合的項目
更改延遲計時器
- 相關問題 #
- closes #
| 修正前 | 修正後 |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/38bc1ce8-e133-49ac-9369-721aee63be27) | ![image](https://github.com/user-attachments/assets/60c5a078-1176-4981-90a6-3d065f405a90) |
> fix: delay counter style

- lib/route/image_viewer/image_viewer.dart
- lib/route/report/report.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> fix: ios report image save

- lib/app/page/more/ranking/tabs/precipitation.dart
- lib/app/page/more/ranking/tabs/temperature.dart
- lib/app/page/more/ranking/tabs/wind.dart
- lib/app/page/more/report_list/report_list.dart
- lib/main.dart
- lib/widget/map/map.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> Fix temp rank

- README.md
> 選擇所有符合的項目
- 相關問題 #
- closes #
> chore: added star history to readme

- lib/api/route.dart
- lib/widget/map/map.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> refactor: lb up to api v2

- lib/route/welcome/pages/permission.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> fix: permission

- lib/route/report/report.dart
> 選擇所有符合的項目
修正地震報告深度(注意海嘯)
- 相關問題 #
- closes #
> fix: report depth

- .gitignore
- android/app/src/main/AndroidManifest.xml
- ios/Runner/Info.plist
- lib/app/welcome/4-permissions/page.dart
- lib/route/image_viewer/image_viewer.dart
> 選擇所有符合的項目
改成僅限加入照片，不存取相簿
- 相關問題 #
- closes #
> fix: photos Permission

- android/app/src/main/AndroidManifest.xml
- lib/app/welcome/4-permissions/page.dart
- lib/route/image_viewer/image_viewer.dart
> 選擇所有符合的項目
Android 修正存取權限
- 相關問題 #
- closes #
> fix: Permission Photos

- .github/workflows/android.yml
- .github/workflows/ios.yml
> 選擇所有符合的項目
修正 build workflow 阻擋 PR 合併的問題
- 相關問題 #
- closes #
> ci: fix path filtering

- android/app/build.gradle
> 選擇所有符合的項目
避免在建構過程中因 Jetifier 處理該 .jar 檔時導致 Java Heap Space 錯誤。
- 相關問題 #
- closes #
> ci: android-exclude-x86

- README.md
> 選擇所有符合的項目
根據 https://branding.twds.com.tw/ 中新的使用指南，更新 README.md 中的 Logo
> Updated Logo for TWDS

- CHANGELOG.md
- android/app/build.gradle
- lib/app/map/_lib/managers/monitor.dart
- lib/app/map/page.dart
- pubspec.lock
- pubspec.yaml
* Changes before Firebase Studio auto-run
* feat: monitor time
* docs: changelog
* build: 300001417
* chore: time
* style: lint
* chore: monitor time
* docs: changelog
* fix
---------
> 選擇所有符合的項目
- 相關問題 #
- closes #
> feat: monitor clock (#330)

- lib/app/settings/notify/page.dart
> 選擇所有符合的項目
修復設定通知初始化沒設定所在地畫面為空白的問題
- 相關問題 #
- closes #
> fix: notify_enabled

- lib/app/map/_lib/managers/radar.dart
- lib/widgets/map/map.dart
> 選擇所有符合的項目
修復 雷達圖層 被覆蓋問題
- 相關問題 #
- closes #
> fix(map/radar): radar layer

- lib/app/settings/location/page.dart
- lib/app/settings/location/select/[city]/page.dart
- lib/models/settings/location.dart
- lib/widgets/list/list_tile.dart
> 選擇所有符合的項目
將手動位置改成多個位置設定，更快速切換
- 相關問題 #
- closes #
> feat: favorite locations

- .github/workflows/ios.yml
- ios/Podfile.lock
- lib/global.dart
- lib/models/data.dart
- pubspec.lock
- pubspec.yaml
> 選擇所有符合的項目
Android  啟動時間縮短約 250-300 ms
Apple 啟動時間縮短約 200 ms
- 相關問題 #
- closes #
> chore: improved startup time

- android/app/build.gradle
- pubspec.yaml
> 選擇所有符合的項目
- 相關問題 #
- closes #
> Build: 3.0.200

- lib/core/notify.dart
> 選擇所有符合的項目
通知導向頁面
地震報告
公告
- 相關問題 #
- closes #
> feat: click notifications

- lib/api/model/history/history.dart
- lib/widgets/home/event_list_route.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> fix(history): workandclassSuspension type

- .crowdin/strings.pot
- assets/translations/en.po
- assets/translations/ja.po
- assets/translations/ko.po
- assets/translations/ru.po
- assets/translations/vi.po
- assets/translations/zh-Hans.po
- assets/translations/zh-Hant.po
- lib/app/map/_widgets/layer_toggle_sheet.dart
- tools/update_translations.sh
> 選擇所有符合的項目
- 相關問題 #
- closes #
> i18n: layer sheet use shorter term

- lib/app/home/_widgets/eew_card.dart
- lib/app/map/_lib/managers/monitor.dart
> 選擇所有符合的項目
- 相關問題 #
- closes #
> fix: text size

- lib/app/settings/location/page.dart
- lib/app/welcome/4-permissions/page.dart
- pubspec.lock
- pubspec.yaml
> 選擇所有符合的項目
移除 autostarter 套件
- 相關問題 #
- closes #
> autostarter

- android/app/build.gradle
- lib/models/data.dart
- lib/route/event_viewer/intensity.dart
- lib/route/event_viewer/thunderstorm.dart
- pubspec.yaml
> 選擇所有符合的項目
修正部分頁面地點沒有級別的問題
- 相關問題 #
- fixes #389 
> fix: city town with level
